title: 'High Fidelity Documentation'
default_lang: en
author:
  name: 'Jenna'
  email: jenna@highfidelity.io
taxonomies:
  - category
  - tag
  - api
  - reference
metadata:
  description: 'High Fidelity Documentation'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /get-started/what-is-high-fidelity/how-it-works: /explore/get-started/architecture
  /get-started/what-is-high-fidelity: /explore/get-started/architecture
  /get-started/requirements: /explore/get-started/install
  /get-started/installation/client-install: /explore/get-started/install
  /get-started/installation/client-and-sandbox-install: /explore/get-started/install
  /get-started/installation/installer-interactions: /explore/get-started/install
  /get-started/installation: /explore/get-started/install
  /get-started/join-us: /contribute
  /get-started/join-us/worklist: /contribute/work-for-us
  /get-started/community: /contribute/engage-with-us
  /get-started: /home  
  /create-and-explore/entering-high-fidelity: /explore
  /create-and-explore/explore-interface/menu/emote: /explore/socialize#express-yourself
  /create-and-explore/explore-interface/menu: /explore/get-started/adjust-settings
  /create-and-explore/explore-interface/basic-controls: /explore/get-started
  /create-and-explore/explore-interface/tablet: /explore/get-started/adjust-settings
  /create-and-explore/explore-interface: /explore
  /create-and-explore/start-working-in-your-sandbox/server-settings-for-your-domain: /host/your-domain/configure-settings
  /create-and-explore/start-working-in-your-sandbox/set-up-your-sandbox: /host/your-domain
  /create-and-explore/start-working-in-your-sandbox/assignment-clients/baking: /host/manage-your-domain-assets
  /create-and-explore/start-working-in-your-sandbox/assignment-clients: /host/manage-your-domain-assets
  /create-and-explore/start-working-in-your-sandbox/place-names: /host/add-a-place-name
  /create-and-explore/start-working-in-your-sandbox/groups-and-lists: /host/your-domain/secure-domain
  /create-and-explore/start-working-in-your-sandbox/set-path-in-your-domain: /host/your-domain/configure-settings#paths
  /create-and-explore/start-working-in-your-sandbox/setting-up-a-theater-domain: /host/theater-domain-tutorial
  /create-and-explore/start-working-in-your-sandbox/hosting-on-other-services: /host/host-your-domain
  /create-and-explore/start-working-in-your-sandbox/migrate-your-sandbox: /host/backup-restore-domain
  /create-and-explore/start-working-in-your-sandbox/digital-ocean: /host/host-your-domain
  /create-and-explore/start-working-in-your-sandbox/restoring-sandbox-content/backup-entities: /host/backup-restore-domain
  /create-and-explore/start-working-in-your-sandbox/restoring-sandbox-content/backup-sandbox: /host/backup-restore-domain
  /create-and-explore/start-working-in-your-sandbox/restoring-sandbox-content: /host/backup-restore-domain
  /create-and-explore/start-working-in-your-sandbox/hosting-your-content: /host/host-your-domain
  /create-and-explore/start-working-in-your-sandbox/broadcasting: /host/broadcast-your-domain
  /create-and-explore/start-working-in-your-sandbox/creating-and-securing-your-domain: /host/your-domain
  /create-and-explore/start-working-in-your-sandbox/streaming/streaming-audio: /host/stream-domain
  /create-and-explore/start-working-in-your-sandbox/streaming/streaming-video: /host/stream-domain
  /create-and-explore/start-working-in-your-sandbox/streaming: /host/stream-domain
  /create-and-explore/start-working-in-your-sandbox: /host
  /create-and-explore/entities/create-mode: /create/entities/create-entities
  /create-and-explore/entities/box-and-sphere-entities: /create/entities/create-entities
  /create-and-explore/entities/light-entities: /create/entities/create-spotlight
  /create-and-explore/entities/web-entities: /create/entities/display-youtube
  /create-and-explore/entities/particle-entities: /create/entities/create-entities
  /create-and-explore/entities/text-entities: /create/entities/create-entities
  /create-and-explore/entities/zone-entities: /create/entities/create-entities
  /create-and-explore/entities/zone-entities/zone-properties: /create/entities/entity-appearance
  /create-and-explore/entities/model-entities: /create/entities/create-entities
  /create-and-explore/entities/collision-sounds: /create/entities/add-sounds
  /create-and-explore/entities/entity-properties: /create/entities/entity-behavior
  /create-and-explore/entities: /create/entities
  /create-and-explore/avatars/how-do-avatars-work: /explore/personalize-experience/change-avatar
  /create-and-explore/avatars/change-avatar: /explore/personalize-experience/change-avatar
  /create-and-explore/avatars/create-avatars/avatar-standards: /create/avatars/create-avatars/avatar-standards
  /create-and-explore/avatars/create-avatars/unity-extension: /avatars/find-avatars
  /create-and-explore/avatars/create-avatars/community: /create/avatars/create-avatars#community-tools-for-avatars
  /create-and-explore/avatars/create-avatars/fuse-tutorial: /create/avatars/fuse-tutorial
  /create-and-explore/avatars/create-avatars/mixamo-tutorial: /create/avatars/mixamo-tutorial
  /create-and-explore/avatars/create-avatars/blender-tutorial: /create/avatars/blender-tutorial
  /create-and-explore/avatars/create-avatars: /create/avatars/create-avatars
  /create-and-explore/avatars/host-avatar: /create/avatars/host-avatar
  /create-and-explore/avatars/avatar-wearables: /explore/personalize-experience/add-wearables
  /create-and-explore/avatars/avatar-interactions: /create/entities/avatar-interactions
  /create-and-explore/avatars/create-avatar-with-flow: /create/avatars/create-avatars/add-flow
  /create-and-explore/avatars/host-avatar-on-marketplace: /create/avatars/host-avatar
  /create-and-explore/avatars: /create/avatars
  /create-and-explore/all-about-scripting/default-scripts: /script/get-started-with-scripting
  /create-and-explore/all-about-scripting/run-scripts: /script/get-started-with-scripting#load-and-run-a-script
  /create-and-explore/all-about-scripting/avatar-scripts: /script/avatar-scripts
  /create-and-explore/all-about-scripting/attach-entity-scripts/client-entity-scripts: /script/client-entity-scripts
  /create-and-explore/all-about-scripting/attach-entity-scripts/server-entity-scripts: /script/server-entity-scripts
  /create-and-explore/all-about-scripting/attach-entity-scripts: /script/get-started-with-scripting
  /create-and-explore/all-about-scripting/assignment-client-scripts: /script/assignment-client-scripts
  /create-and-explore/all-about-scripting/scripting-console: /script/get-started-with-scripting#scripting-console
  /create-and-explore/all-about-scripting: /script
  /create-and-explore/3d-modeling/materials/pbr-materials-guide: /create/3d-models/pbr-materials-guide
  /create-and-explore/3d-modeling/materials/material-guide: /create/3d-models/pbr-materials-guide
  /create-and-explore/3d-modeling/materials: /create/3d-models/pbr-materials-guide
  /create-and-explore/3d-modeling/best-practices: /create/3d-models/get-model
  /create-and-explore/3d-modeling/create-buildings: /create/3d-models/buildings-tutorial
  /create-and-explore/3d-modeling/blocks-to-hifi: /create/3d-models/get-model
  /create-and-explore/3d-modeling: /create/3d-models
  /create-and-explore/marketplace-apps/record-app: /explore/personalize-experience/install-apps
  /create-and-explore/marketplace-apps/spectator-cam: /explore/personalize-experience/install-apps
  /create-and-explore/marketplace-apps/shapes: /explore/personalize-experience/install-apps
  /create-and-explore/marketplace-apps: /explore/personalize-experience/install-apps
  /create-and-explore/software-options: /create/tools
  /create-and-explore/live-streaming/intro-to-live-streaming: /host/stream-domain
  /create-and-explore/live-streaming/obs-guide: /host/stream-domain
  /create-and-explore/live-streaming: /host/stream-domain
  /create-and-explore: /home
  /learn-with-us/setup-your-domain-to-build: /host/your-domain  
  /learn-with-us/get-started-with-scripting: /script
  /learn-with-us/all-about-entity-scripts: /script/client-entity-scripts
  /learn-with-us/create-an-avatar-switching-tablet-app: /create/applications
  /learn-with-us/scripting-basics: /script/write-scripts
  /learn-with-us/create-a-tablet-app: /create/applications
  /learn: /script
  /high-fidelity-commerce/basics/hfc/get-hfc: /explore/bank-and-shop
  /high-fidelity-commerce/basics/hfc/send-money: /explore/socialize#send-hfc-to-others
  /high-fidelity-commerce/basics/hfc: /explore/bank-and-shop
  /high-fidelity-commerce/basics/pop/pop-license: /sell/own-item
  /high-fidelity-commerce/basics/pop: /sell/own-item
  /high-fidelity-commerce/basics: /explore/bank-and-shop
  /high-fidelity-commerce/avatar-wearables/buy: /explore/personalize-experience/add-wearables
  /high-fidelity-commerce/avatar-wearables/create: /create/wearables
  /high-fidelity-commerce/avatar-wearables: /explore/personalize-experience/add-wearables
  /high-fidelity-commerce/commerce-apis/tip-jar-example: /script/transfer-hfc-tutorial
  /high-fidelity-commerce/commerce-apis/paid-entry-example: /script/transfer-hfc-tutorial
  /high-fidelity-commerce/commerce-apis/slot-machine-example: /script/transfer-hfc-tutorial
  /high-fidelity-commerce/commerce-apis: /script/transfer-hfc-tutorial
  /high-fidelity-commerce: /explore/bank-and-shop
  /marketplace/buy: /explore/bank-and-shop
  /marketplace/sell/add-item: /sell/add-item
  /marketplace/sell/test-item: /create/tools#marketplace-item-tester
  /marketplace/sell/update-item: /sell/update-item
  /marketplace/sell/create: /sell/add-item/upload-wearable
  /marketplace/sell: /sell
  /marketplace/certifiedapps: /sell/certified-apps
  /marketplace/submissionrules: /sell/submission-rules
  /marketplace/billofrights: /sell/bill-of-rights
  /marketplace: /sell
  /build-guide/basic-build-guide: /contribute/build-guide
  /build-guide/linux/cheatsheet-for-install-linux: /contribute/build-guide/linux
  /build-guide/linux: /contribute/build-guide/linux
  /build-guide/mac-os: /contribute/build-guide/os-x
  /build-guide/windows-64-bit: /contribute/build-guide/windows-64-bit
  /build-guide/android: /contribute/build-guide/android
  /build-guide/clean-installs: /explore/get-started/install#perform-a-clean-installation
  /build-guide: /contribute/build-guide
  /write-for-us: /contribute
blog:
  route: /blog
