enabled: true
top_level_version: true
show_all_pages: false
github:
  position: top
  tree: 'https://github.com/highfidelity/hifi-docs-grav-content'
  commits: 'https://github.com/highfidelity/hifi-docs-grav-content'
